---
- name: cisco
  hosts: switchs
  connection: network_cli
  gather_facts: no
  tasks:
    - name: Set default switch name
      cisco.ios.ios_config:
              lines: hostname Switch


    - name: Delete Vlans
      cisco.ios.ios_vlans:
            config:
            - vlan_id: 10
            - vlan_id: 20
            - vlan_id: 30
            state: deleted
